### ISSUE TITLE
v2 checklist

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#52]
After a quick pass through the online demos, it appears that the v2 branch is not ready for merging just yet. Here is a list of the things that we need to address to make an initial 2.0 release:

- [x] IN - grouping headers (combobox, ddl)
- [x] IN - datetimepicker icons alignment
-  datetimepicker icons should be stretched (currently clicks outside them can land on k-select and not open the picker) -> this is the default behavior of DateTimePicker. We should think about changing this behavior (breaking change)
- [x] IN - calendar selected today date background and foreground color are the same
- [x] IN - drop-down list icons are not vertically aligned
- [x] GYO - editor table width is missing
- [x] OR - editor icons color & layout
- [x] GYO - window k-overlay is not styled
- [x] IN - window icon colors
- [x] maskedtextbox layout
- [x] GYO - numerictextbox buttons
- [x] IN - slider - tooltip positioning is not right (probably due to animations?)
- [x] OR - upload - remove button is not right-aligned
- [x] OR - no styles for k-textbox (https://github.com/telerik/kendo-theme-default/issues/49)
- [x] GYO - switch, buttongroup have no styles due to km-styles (https://github.com/telerik/kendo/pull/6129)
- [x] IN - switch - labels do not get properly hidden
- [x] scrollview - appears to be missing layout
- [x] button demos - remove text from icon, review icons
- menu - no borders at all -> By design there aren't any borders
- [ ] menu - forecolor of expanded items
- [x] GYO - panelbar - k-image alignment
- [x] IN - tabstrip border exists between selection and content
- [ ] gantt, scheduler
- [x] IN - notification text in icons
- [x] OR - splitter drag styles
- [x] ZH - grid grouping icon text
- [ ] spreadsheet
- [x] IN - pager: add border by default, remove when nested
- [ ] mediaplayer - red borders
- [x] GYO - touch scroller is not styled (affects map)
- [x] GYO - dataviz - themes should be either defined in JSON for the kendo components, or the style functionality ported

- [ ] Kendo Notification close button is displaced with the Default skin [#78]( https://github.com/telerik/kendo-theme-default/issues/78)

Any contribution to the list (checking off, or adding new items) is welcome!

**Comment by gyoshev** [comment]
v2 is out, remaining issues for the R1 release are tracked in another issue.
